config/routes.rb
Rails.application.routes.draw do
  resources :publishing_companies
  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
end

app/models/publishing_company.rb
class PublishingCompany < ActiveRecord::Base
  belongs_to :prefecture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :description, :price)
    end
end

app/controllers/publishing_companies_controller.rb
class PublishingCompaniesController < ApplicationController
  before_action :set_publishing_company, only: [:show, :edit, :update, :destroy]

  # GET /publishing_companies
  # GET /publishing_companies.json
  def index
    @publishing_companies = PublishingCompany.joins(:prefecture).all
  end

  # GET /publishing_companies/1
  # GET /publishing_companies/1.json
  def show
  end

  # GET /publishing_companies/new
  def new
    @publishing_company = PublishingCompany.new
  end

  # GET /publishing_companies/1/edit
  def edit
  end

  # POST /publishing_companies
  # POST /publishing_companies.json
  def create
    @publishing_company = PublishingCompany.new(publishing_company_params)

    respond_to do |format|
      if @publishing_company.save
        format.html { redirect_to @publishing_company, notice: 'Publishing company was successfully created.' }
        format.json { render :show, status: :created, location: @publishing_company }
      else
        format.html { render :new }
        format.json { render json: @publishing_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishing_companies/1
  # PATCH/PUT /publishing_companies/1.json
  def update
    respond_to do |format|
      if @publishing_company.update(publishing_company_params)
        format.html { redirect_to @publishing_company, notice: 'Publishing company was successfully updated.' }
        format.json { render :show, status: :ok, location: @publishing_company }
      else
        format.html { render :edit }
        format.json { render json: @publishing_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishing_companies/1
  # DELETE /publishing_companies/1.json
  def destroy
    @publishing_company.destroy
    respond_to do |format|
      format.html { redirect_to publishing_companies_url, notice: 'Publishing company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publishing_company
      @publishing_company = PublishingCompany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publishing_company_params
      params.require(:publishing_company).permit(:name, :description, :prefecture_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/publishing_companies_helper.rb
module PublishingCompaniesHelper
end

app/views/publishing_companies/_form.html.erb
<%= form_for(@publishing_company) do |f| %>
  <% if @publishing_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publishing_company.errors.count, "error") %> prohibited this publishing_company from being saved:</h2>

      <ul>
      <% @publishing_company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :prefecture_id %><br>
    <%= f.number_field :prefecture_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishing_companies/edit.html.erb
<h1>Editing Publishing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @publishing_company %> |
<%= link_to 'Back', publishing_companies_path %>

app/views/publishing_companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Publishing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Prefecture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishing_companies.each do |publishing_company| %>
      <tr>
        <td><%= publishing_company.name %></td>
        <td><%= publishing_company.description %></td>
        <td><%= publishing_company.prefecture_id %></td>
        <td><%= link_to 'Show', publishing_company %></td>
        <td><%= link_to 'Edit', edit_publishing_company_path(publishing_company) %></td>
        <td><%= link_to 'Destroy', publishing_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publishing company', new_publishing_company_path %>

app/views/publishing_companies/new.html.erb
<h1>New Publishing Company</h1>

<%= render 'form' %>

<%= link_to 'Back', publishing_companies_path %>

app/views/publishing_companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publishing_company.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @publishing_company.description %>
</p>

<p>
  <strong>Prefecture:</strong>
  <%= @publishing_company.prefecture_id %>
</p>

<%= link_to 'Edit', edit_publishing_company_path(@publishing_company) %> |
<%= link_to 'Back', publishing_companies_path %>